FROM nginx:alpine

# Copiar build gerado manualmente (para evitar erros de stream no build do docker)
COPY dist /usr/share/nginx/html

# Copiar configuração personalizada do Nginx (para SPA)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
